### PR TITLE
Create federated presence doc under "Shared practices" category

### PR DESCRIPTION
**Pull request by gabek**
This is categorized under "Actions" but I'm not sure that's a great name. I didn't want to use "Activities" because that refers to a specific term in ActivityPub, and "Standards" feels like it's from a standards body.

What I'm trying to say is "Common things that can happen on the Fediverse that multiple projects have agreed is the way to do it". Is "Actions" a name for that?

Will from Immers Space will add examples.

### CODE REVIEW

**Comment by gabek** [comment]
Johannes suggested "Shared practices" and I think that's sufficiently vague and describes what this is, so I renamed it to that.

**Comment by Johann150** [comment]
> #### What is it not?
> - It is not for changes or enhancements to the specs. See the [Fediverse Enhancement Proposals](https://codeberg.org/fediverse/fep).

Going from the above I think the proper term/way would be a FEP? Or are we already throwing that decision out again?

**Comment by Johann150** [comment]
I'm not sure what this section is supposed to be. The "name-lawyering" to avoid calling it a "standard" doesn't really help. If it is merely about "what different projects are doing" would it not be more fitting to document it for the individual projects, perhaps having a "same as xyz implementation" hint or outright making it a link a la "see xyz implementation"? (Of course the latter would be a problem when something changes, but keeping things up to date would probably be an issue either way.)

Since this is about discussing interoperability between different applications, I believe it also fits this self-definition of what a FEP is:

> The goal of a FEP is to improve interoperability and well-being of diverse services, applications and communities that form the Fediverse.
-- https://codeberg.org/fediverse/fep/#fediverse-enhancement-proposals

If you think this does not need to be a FEP, I think the statement I quoted from "what this is not" should be revised to make that distinction.

**Comment by gabek** [comment]
This isn't looking to make a change to the spec or enhance anything. It's simply to document "hey, we're doing X this way, if you want to do X too, here's how you do it". The name is "shared practices" because it's a practice shared, not a standard as established by a standards body.

It's purely for the goal of documenting, not for changing.

**Comment by jernst** [comment]
I'm going out on a limb here and just start merging, on the grounds that I claim progress is good :-)

**Pull request merged**
